### ISSUE TITLE
Wrong Lists Web Service End point url 

### ISSUE THREAD

**Issue by tonilcaiser** [inclinetechnical/QuickCAML#2] opened 2015-06-26 10:56 UTC
At line 869 the ajax call to web service is done to retrieve information upon query caml built.
jQuery.ajax({
                url: ctx.get_url() + Constants.ListServiceUrl,
                type: 'POST',
                dataType: 'xml',
                data: Constants.SoapEnvStart + soapBody + Constants.SoapEnvEnd,
                contentType: 'text/xml; charset="utf-8"'
            })
But cxt.get_url() has not been loaded, so the url parameter would be like http://_vti_bin/lists.asmx that obviously is wrong.

My change is:
jQuery.ajax({
                url: _spPageContextInfo.webAbsoluteUrl+ "/" + Constants.ListServiceUrl,
                type: 'POST',
                dataType: 'xml',
                data: Constants.SoapEnvStart + soapBody + Constants.SoapEnvEnd,
                contentType: 'text/xml; charset="utf-8"'
            })
as _spPageContextInfo.webAbsoluteUrl is always available in page without JSOM or CSOM.

In this way, it works!

**Comment by inclinetechnical** [comment] 2015-06-26 19:58
Are you using on-premise SharePoint 2013 or SharePoint Online? I'll likely update the code base to include your change, but I'm curious which version of SP you're using since I've never seen that. "ctx.get_url()" at line 869 has always been loaded for me.

Also, can you tell me what browser you were using? That might be related to this too. Thanks!

**Comment by inclinetechnical** [comment] 2016-01-20 21:30
Closing this issue because no comments have been made on it since June of 2015, and I still haven't seen this URL problem in any environment I've tested in. It may have been caused by customizations in the OP's environment or some other one-off issue.

**Closed as completed by inclinetechnical** 2016-01-20 21:30 UTC
Labels: bug
